title: Iszak Bryan
description: "Web Application Developer"
baseurl: ""
url: "http://iszak.net"

highlighter: true
permalink: /:year/:month/:day/:title.html

author:
  name: Iszak Bryan
  github: iszak
  twitter: iszak
  gplus: 100069654061825702190


gems:
  - jekyll-assets

assets:
  js_compressor: uglifier
  css_compressor: sass

  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
    - _assets/fonts/vendor/

exclude: ['vendor']
